### ISSUE TITLE
toxic drop

### ISSUE THREAD

**Issue by jprentals** [cassidyjames/jppartyrentals.com#24]
this is our most expensive rental and our most unique one so we need to showcase it well. it is the only one exactly like it in Iowa.

the toxic drop is the giant black and yellow pictures I sent you.

Toxic Drop
78′ x 12′ x 16′
$1,200

The toxic drop is our signature obstacle course featuring 7 unique obstacles.
Obstacle 1. The Wedges
Obstacle 2. The X Wall
Obstacle 3. The Vault
Obstacle 4. The Mangle
Obstacle 5. The Blocks
Obstacle 6. The Drop 
Obstacle 7. The Slide
the toxic drop is sure to take your event to the next level!

**Comment by cassidyjames** [comment]
I might want to add a feature to the site where we can provide multiple photos and it cycles between them... not sure exactly how that will look yet, but that way we could feature multiple photos/angles.

**Comment by cassidyjames** [comment]
Initial section added until I can figure out a multi-photo thing or something. I had to shorten the text a bit so it'd fit in the same number of lines as the others.
