### ISSUE TITLE
Dunk tank

### ISSUE THREAD

**Issue by jprentals** [cassidyjames/jppartyrentals.com#30]
I do not have I picture for this yet

**Comment by cassidyjames** [comment]
Let me know when you do!

**Comment by jprentals** [comment]
Dunk tank and pucker powder pictures have been sent via dropbox.

Jordan Henry
JP Party rentals
www.jppartyrentals.com
515-988-7604

**Comment by jprentals** [comment]
Dunk tank is $200 and pucker powder can say call for pricing

Jordan Henry
JP Party rentals
www.jppartyrentals.com
515-988-7604
